org: tonyxuan2022
app: quote-projec
service: quote-projec

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  memorySize: 128

plugins:
  - serverless-wsgi
  - serverless-python-requirements
custom:
  pythonRequirements:
    pythonBin: python3
  wsgi:
    app: app.app
    packRequirements: false
functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"
